# Generated by Django 5.0.1 on 2024-02-16 15:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_assetsmodel_assetslogmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetsmodel',
            name='purchased_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
